### ISSUE TITLE
Error: The following CloudFormation Parameters are missing a value

### ISSUE THREAD

**Issue by cannahum** [bodokaiser/aws-cdk-codepipeline-lambda-go#1]
Hi!

I've been trying to build CDK-based stacks and a Pipeline stack for myself too when I came across your repository. I've been running into the error: **The following CloudFormation Parameters are missing a value**

I figured I'd give your repo a try just to see how you got around it. When I cloned your repo and tried deploying the PetsPipelineStack, I got the same issue:
```
PetsLambdaStack failed: Error: The following CloudFormation Parameters are missing a value: LambdaLambdaSourceBucketNameParameter159473FC, LambdaLambdaSourceObjectKeyParameter06573F1D
```

I wonder what the solution is... 

The Codebuild project obviously knows the values of the bucket name and the Object key; how do we pass them to the deployment stage? And why does the Pipeline stack fail!? Anyway... Thanks for the example.

**Comment by bodokaiser** [comment]
You cannot deploy the lambda from the command line. AWS CodeBuild has to build and deploy the lambda for you.

When you try to deploy stacks referencing the Lambda, `cdk` tries to deploy the dependent `LambdaStack`. A workaround is to use `npx cdk -e deploy YourStack` as the `-e` flag *exclusively* deploys a stack ignoring its dependencies.

**Comment by cannahum** [comment]
That's it?! `-e` was all I was missing? I spent days on this, trying to understand why running `cdk deploy PipelineStack` is pulling all the other stacks into the mix...
Thank you so much for your direction here. I hope AWS can improve their example documentation.
